### ISSUE TITLE
AndroidX Support

### ISSUE THREAD

**Issue by zurtox** [tritondigital/android-sdk#3]
On november 20th, 2020; Google announced all the applications MUST be targetting Android API 29, which it supports Android X and library support will be deprecated.

Is there any release date with those changes on the SDK?

**Comment by vlazdra** [comment]
Hi, since I was interested in the same thing and more, I made a fork of the Triton repo.
If you want to try it out you can go here: [https://github.com/vlazdra/triton-android-sdk](https://github.com/vlazdra/triton-android-sdk)

Just go thought the README.md file to integrate and that's it.

**Comment by jd-buys** [comment]
We have also implemented AndroidX support.
